(define (cons x y)
  (* (expt 2 x) (expt 3 y)))

(define (car z)
  (define (helper x y)
    (if (= (remainder x 2) 0)
        (helper (/ x 2) (+ y 1))
        y))
  (helper z 0))

(define (cdr z)
  (define (helper2 x y)
    (if (= (remainder x 3) 0)
        (helper2 (/ x 3) (+ y 1))
        y))
  (define (helper x y)
    (if (= (remainder x 2) 0)
        (helper (/ x 2) (+ y 1))
        (helper2 x 0)))
  (helper z 0))
