(define (call-the-cops)
  (display "Calling the cops")
  (newline))

(define (make-account balance pass)
  (let ((failed-attempts 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch supplied-pass msg)
      (if (eq? supplied-pass pass)
          (cond ((eq? msg 'withdraw) withdraw)
                ((eq? msg 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACCOUNT"
                             msg)))
          (if (>= failed-attempts 7)
              (call-the-cops)
              (begin
                (set! failed-attempts (+ failed-attempts 1))
                (error "Incorrect password")))))
    dispatch))
