(define (make-crypted-account balance pass)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch supplied-pass msg)
    (if (eq? supplied-pass pass)
        (cond ((eq? msg 'withdraw) withdraw)
              ((eq? msg 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           msg)))
        (error "Incorrect password")))
  dispatch)

(define (make-joint-account account password joint-account-password)
  (lambda (supplied-password msg)
    (if (eq? supplied-password joint-account-password)
        (account password msg)
        (error "Invalid joint account password"))))
